# CONVOLUTION

In [10]:
import numpy as np
def conv_1D(signal, kernel):
    
    n = len(signal)
    k = len(kernel)
    
    pad_size = k//2
    padded_signal = [0]*pad_size + signal + [0]*pad_size
    
    output = np.zeros(n)
    
    kernel = np.array(kernel)
    padded_signal = np.array(padded_signal)
    
    for i in range(n):
        print(i)
        output[i] = np.sum(kernel*padded_signal[i:i+k])
    return output

signal = [1, 2, 3, 4, 5, 6]
kernel = [1, 0, -1]
output = conv_1D(signal, kernel)
print(output)
        
        

0
1
2
3
4
5
[-2. -2. -2. -2. -2.  5.]


In [16]:
import numpy as np

def conv_3D(image, kernel):
    (image_h, image_w, image_ch) = image.shape
    (kernel_h, kernel_w, input_ch, output_ch) = kernel.shape
    
    pad_h = kernel_h // 2
    pad_w = kernel_w // 2
    
    padded_image = np.pad(image, pad_width=((pad_h, pad_h), (pad_w, pad_w), (0, 0)), mode='constant', constant_values=0)
    output = np.zeros((image_h, image_w, output_ch))
    
    for i in range(image_h):
        for j in range(image_w):
            for k in range(output_ch):
                output[i, j, k] = np.sum(kernel[:, :, :, k] * padded_image[i:i+kernel_h, j:j+kernel_w, :])
    
    return output

# Example usage with properly shaped image and kernel
image = np.random.randn(5, 5, 3)  # Example input image with height=5, width=5, channels=3
kernel = np.random.randn(3, 3, 3, 2)  # Example 3x3 kernel for 3 input channels and 2 output channels

# Perform the convolution operation
output = conv_3D(image, kernel)

print('Input image shape:', image.shape)
print('Kernel shape:', kernel.shape)
print('Output shape:', output.shape)

print('\nInput image:')
print(image)

print('\nKernel:')
print(kernel)

print('\nOutput:')
print(output)


Input image shape: (5, 5, 3)
Kernel shape: (3, 3, 3, 2)
Output shape: (5, 5, 2)

Input image:
[[[ 2.39871416 -0.90787964  0.90607533]
  [-0.44174006  1.26408205  0.32574084]
  [-1.32462152  1.13639416 -1.44453008]
  [ 1.11944979 -0.63964524  0.06375501]
  [-1.31562609 -0.40896135  0.48625223]]

 [[-0.04714234 -0.40404103  0.18782059]
  [ 0.56862336  1.83924503 -1.16565465]
  [-0.76308274  0.21070431  0.18656453]
  [ 0.13447991 -0.60445593  0.39338867]
  [ 0.98949342 -0.88363288 -0.37520259]]

 [[ 0.23804468  0.96877513 -1.11911282]
  [-0.51095294  1.23022587 -0.0514882 ]
  [-0.32319218  0.49401397 -0.50721202]
  [ 0.54591013 -0.11429208 -2.90825637]
  [-0.69437522  0.59248191 -0.44773474]]

 [[-0.73166258  1.30816632 -0.3331178 ]
  [-0.96423724  0.55100071  1.50588405]
  [-0.76692547 -1.33716801  1.3221799 ]
  [-1.37321855 -1.83118162  0.80723937]
  [-1.48523662 -1.27410191 -0.817419  ]]

 [[ 0.22240953  0.205003   -0.40239014]
  [-1.20530925 -0.8464857  -2.25587785]
  [-0.27719902 -0.