# LINEAR REGRESSION

# Single Variable Case:
#### y = mx + b
#### Loss = L = sum[(mx + b - y)^2]


### Partial Derivatives:
#### dL/dm = sum[2(mx + b - y)x]
#### dL/db = sum[2(mx + b - y)]


### Find b in terms of m and x,y values, plug into the first equation, and solve for m:
#### m = sum[(x - x_mean)(y - y_mean)] / sum[(x - x_mean)^2]
#### b = y_mean - m*x_mean

In [18]:
from typing import List
import numpy as np

class LinearRegressor():
    def __init__(self):
        self.m = None
        self.b = None
        
    def fit(self, x: List[int], y: List[int]):
        x_mean = np.mean(x)
        y_mean = np.mean(y)
        n = len(x)
    
        x_sqr_mean  = 0
        xy_mean = 0
        for i in range(n):
            x_sqr_mean += x[i]**2
            xy_mean += x[i]*y[i]
        
        x_sqr_mean /= n
        xy_mean /= n
        
        self.m = (xy_mean - x_mean*y_mean)/(x_sqr_mean - x_mean**2)
        #self.b = y_mean - self.m * x_mean
        self.b = (y_mean*x_sqr_mean - x_mean*xy_mean)/(x_sqr_mean - x_mean**2)
        
    def results(self):
        return (self.m, self.b)
    
    def predict(self, x):
        return self.m*x + self.b
        

In [19]:
x = [1, 1.9, 3.1, 4, 4.7]
y = [4, 6.3, 7.7, 9.5, 12.0]

linreg = LinearRegressor()
linreg.fit(x,y)
m,b = linreg.results()
print(m,b)

1.9918609766827995 2.0439287285525714


To make it more efficient, we can convert the lists to numpy arrays and use numpy's efficient sum functions:

In [20]:
from typing import List
import numpy as np

class LinearRegressor():
    def __init__(self):
        self.m = None
        self.b = None
        
    def fit(self, x: List[int], y: List[int]):
        x = np.asarray(x)
        y = np.asarray(y)
        x_mean = np.mean(x)
        y_mean = np.mean(y)
        n = len(x)
    
        nominator_m = np.sum((x-x_mean)*(y-y_mean))
        denominator_m = np.sum((x-x_mean)**2)
        
        self.m = nominator_m/denominator_m
        self.b = y_mean - self.m * x_mean
        
    def results(self):
        return (self.m, self.b)
    
    def predict(self, x):
        return self.m*x + self.b

In [21]:
x = [1, 1.9, 3.1, 4, 4.7]
y = [4, 6.3, 7.7, 9.5, 12.0]

linreg = LinearRegressor()
linreg.fit(x,y)
m,b = linreg.results()
print(m,b)

1.9918609766827975 2.043928728552576


In [22]:
linreg.predict(9.5)

20.966608007039152

# Many Variable Case

Let y: nx1, W: dx1, X: nxd dimensions. n is the sample size. First column of the X matrix will be 1 for all samples, it will be multiplied with w_0 and count as the bias term. This derivation leads to:

$$
\mathbf{W} = (\mathbf{X}^\top \mathbf{X})^{-1} \mathbf{X}^\top \mathbf{Y}
$$

If we keep d=2, it corresponds to the scalar x scenario. So, with this solution, we also derived the scalar case on top of the vector case

In [1]:
import numpy as np
class LinRegVec():
    def __init__(self):
        self.W = None
        
    def fit(self, X, Y):
        n = X.shape[0]
        X_b = np.ones((n,1))
        X = np.hstack((X_b, X))
        self.W = np.linalg.inv(X.T @ X) @ (X.T @ Y)
        
    def predict(self, X):
        n = X.shape[0]
        X_b = np.ones((n,1))
        X = np.hstack((X_b, X))
        return X @ self.W

In [2]:
# Create example input data
X = np.array([[1, 2], [3, 5], [8, 11]])
y = np.array([8, 19, 45])

# Fit linear regression model
lr = LinRegVec()
lr.fit(X, y)
print(lr.W) 

# Make predictions on new data
X_new = np.array([[10, 11], [13, 14]])
y_pred = lr.predict(X_new)
print(y_pred) 


[2. 4. 1.]
[53. 68.]


In [3]:
lr.W

array([2., 4., 1.])

In [16]:
import numpy as np
a = np.asarray([[1],[2],[3],[4]])
b = np.asarray([[5,6,7,8]])

In [17]:
a @ b


array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

In [4]:
import numpy as np
X = np.array([[1, 1, 2], [1, 3, 5]])
y = np.array([8, 19, 45])

X@y

array([117, 290])

In [6]:
np.dot(X,y)

array([117, 290])

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])